# Copyright 2022-2023 LunarG, Inc.
# Copyright 2023-2024 RasterGrid Kft.
#
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  push:
  pull_request:
    branches:
    - main
    - sc_main

env:
  CMAKE_GENERATOR: Ninja
            
permissions:
    contents: read

jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        cmake-version: [ '3.15', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake-version }} 
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cmake -S . -B build -D BUILD_TESTS=ON -G Ninja
      - run: cmake --build build
      - run: cmake --install build --prefix ${GITHUB_WORKSPACE}/build/install
      - run: ctest --output-on-failure
        working-directory: build

  cmake-combined-headers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        cmake-version: [ '3.15', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake-version }} 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cmake -S . -B build -D BUILD_TESTS=ON -G Ninja -DGEN_VULKANSC_COMBINED=ON
      - run: cmake --build build
      - run: cmake --install build --prefix ${GITHUB_WORKSPACE}/build/install
      - run: ctest --output-on-failure
        working-directory: build

  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v3
